config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  resources :articles do
    resources :comments
  end

  resources :categories, only: :show

  get '/about', to: 'about#index'
  get '/archive', to: 'archive#index'
  get '/contact', to: 'contact#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories

  validates :title, presence: true, length: { minimum: 10 }

  scope :most_recent, -> { where(is_published: true).order(created_at: :desc).limit(5) }
  scope :published, -> { where(is_published: true).order(created_at: :desc) }

  def first_category
    categories.first
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @recent_articles = Article.most_recent
    @categories = Category.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.includes(:articles).find(params[:id])
    @articles = @category.articles.where(is_published: true).page(params[:page])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :email, :text)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.published.includes(:categories).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTML < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet

    def block_code(code, language)
      Rouge.highlight(code, language || 'text', 'html')
    end
  end

  def markdown(text)
    render_options = {
      filter_html:     false,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow' }
    }
    renderer = HTML.new(render_options)

    extensions = {
      autolink:           true,
      fenced_code_blocks: true,
      lax_spacing:        true,
      no_intra_emphasis:  true,
      strikethrough:      true,
      superscript:        true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def date_to_s(date)
    date.strftime('%B, %d %Y')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.slim
== content_for :title, 'Yoyo Coder | About'
== render 'layouts/dark_navbar'
== render 'layouts/home_button'
section.wrapper
  .sub-page.border-bottom-gray
    h2 Yoyo Coder
    h1 About
    p
      i.fa.fa-plane
      | Hi, I'm Yoyo Coder.
    = image_tag 'about-image.jpg'

app/views/archive/index.html.slim
== content_for :title, 'Yoyo Coder | Archive'
== render 'layouts/dark_navbar'
== render 'layouts/home_button'
section.wrapper
  .sub-page.border-bottom-gray
    h1 Archive
    h3 Recent Articles
    .articles.sub
      - @recent_articles.each_with_index do |article, index|
          p
            = "#{index + 1}."
            = link_to article.title, article_path(article)
    h3 Archives by Category:
    .categories.sub
      - @categories.each do |category|
        p
          i.fa.fa-square
          = link_to category.name, category_path(category)

app/views/articles/_right_sidebar_bottom.html.slim
.right-sidebar-bottom
  = image_tag 'me.jpg'
  h2 Yoyo Coder
  p ...
  hr
  h3 LASTEST POSTS
  .recent-articles
    - Article.most_recent.each do |article|
      = link_to article.title, article_path(article)
      p= date_to_s(article.created_at)

app/views/articles/_right_sidebar_top.html.slim
.right-sidebar-top
  = image_tag 'me.jpg'
  h2 Yoyo Coder
  = social_share_button_tag(@article.title, url: article_url(@article), popup: 'true', via: 'Yoyo Coder')
  p ...
  hr

app/views/articles/show.html.slim
== content_for :title, @article.title
== render 'layouts/light_navbar'
#cover
  .background
  header
    h2
      = link_to @article.first_category.name, category_path(@article.first_category) unless @article.first_category.nil?
    h1
      = @article.title
    span
      | Posted by
      span
        = link_to 'Yoyo Coder', about_path
      i.fa.fa-clock-o
      = link_to date_to_s(@article.created_at), '#'
      |.
  .top-sidebar
    = render 'right_sidebar_top'
== render 'layouts/home_button'
== render 'layouts/fixed_header'

.bottom-sidebar
  == render 'right_sidebar_bottom'

section.posts.wrapper#content
  .article.border-bottom-gray
    .text
      = markdown @article.text
  .profile-bottom.border-bottom-gray
    = image_tag 'me.jpg', class: 'avatar'
    .info
      h4 Yoyo Coder
      p If you think you can, you can.
      = social_share_button_tag(@article.title, url: article_url(@article), popup: 'true', via: 'Yoyo Coder')

coffee:
  $ ->
    new Waypoint
      element: $('#content')[0]
      handler: (direction) ->
        if direction == 'down'
          $('#fixed-header').fadeIn()
          if $('.right-sidebar-bottom').length then $('.bottom-sidebar').fadeIn()
          if $('.right-sidebar-top').length then $('.top-sidebar').fadeOut()
        else
          $('#fixed-header').fadeOut()
          if $('.right-sidebar-bottom').length then $('.bottom-sidebar').fadeOut()
          if $('.right-sidebar-top').length then $('.top-sidebar').fadeIn()

app/views/categories/show.html.slim
== render 'layouts/dark_navbar'
== render 'layouts/home_button'
section.wrapper
  .notification
    span.ntitle Category
    span.message= @category.name
    = link_to root_path
      i.fa.fa-times
  .articles
    - @articles.each do |article|
      .article
        .feature
          span Feature
          i.fa.fa-bookmark.fa-lg
        h2
          = link_to article.first_category.name, category_path(article.first_category) unless article.first_category.nil?
        h1
          = link_to article.title, article_path(article), class: 'blog-title'
        span
          | Posted by
          span
            = link_to about_path do
              = image_tag 'me.jpg'
              | Yoyo Coder
          i.fa.fa-clock-o
          = link_to date_to_s(article.created_at), '#'
          |.
        p= markdown truncate(article.text, length: 400)
  - if @articles.length > 10
    .paginator.border-bottom-gray
      span.left= link_to_previous_page @articles, 'Newer Posts'
      span.right= link_to_next_page @articles, 'Older Posts'
== render 'layouts/right_sidebar'

app/views/contact/index.html.slim
== content_for :title, 'Yoyo Coder | Contact'
== render 'layouts/dark_navbar'
== render 'layouts/home_button'
section.wrapper
  .sub-page.border-bottom-gray
    h2 Yoyo Coder
    h1 Contact
    p
      | If you have any questions you can email&#160;
      = link_to 'yoyo.coder@gmail.com', 'mailto:yoyo.coder@gmail.com'
      | , and I will be happy to help.

    = image_tag 'about-image.jpg'

app/views/home/index.html.slim
== render 'layouts/dark_navbar'
section.wrapper
  .articles
    - @articles.each do |article|
      .article
        .feature
          span Featured
          i.fa.fa-bookmark.fa-lg
        h2
          = link_to article.first_category.name, category_path(article.first_category) unless article.first_category.nil?
        h1
          = link_to article.title, article_path(article), class: 'blog-title'
        span
          | Posted by
          span
            = link_to about_path do
              = image_tag 'me.jpg'
              | Yoyo Coder
          i.fa.fa-clock-o
          = link_to date_to_s(article.created_at), '#'
          |.
        .text
          = markdown truncate(article.text, length: 400)
  - if @articles.length > 10
    .paginator.border-bottom-gray
      span.left= link_to_previous_page @articles, 'Newer Posts'
      span.right= link_to_next_page @articles, 'Older Posts'
== render 'layouts/right_sidebar'

app/views/layouts/_analytics.html.slim
- if Rails.env.production?
  = javascript_include_tag "google_analytics"

app/views/layouts/_dark_navbar.html.slim
nav.navbar.navbar-default.dark-navbar.bg-transparent-color.no-border
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#main-menu" aria-expanded="false"
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .collapse.navbar-collapse#main-menu
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Home', root_path
        li
          = link_to 'About', about_path
        li
          = link_to 'Archive', archive_path
        li
          = link_to 'Contact', contact_path
        li
          .toggle
            i.fa.fa-bars

app/views/layouts/_fixed_header.html.slim
#fixed-header.fixed
  .wrapper
    .title= truncate(@article.title, length: 62)

app/views/layouts/_footer.html.slim
footer.wrapper
  p
    | Copyright ©
    = link_to 'Yoyo Coder', '#'
    | . 2016 • All rights reserved.
  p
    | Powered by Yoyo Coder.

app/views/layouts/_home_button.html.slim
.home-icon.fixed
  = link_to root_path
    i.fa.fa-bookmark-o.fa-lg
    span Yoyo Coder

app/views/layouts/_light_navbar.html.slim
nav.navbar.navbar-default.light-navbar.bg-transparent-color.no-border
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#main-menu" aria-expanded="false"
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .collapse.navbar-collapse#main-menu
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Home', root_path
        li
          = link_to 'About', about_path
        li
          = link_to 'Archive', archive_path
        li
          = link_to 'Contact', contact_path
        li
          .toggle
            i.fa.fa-bars

app/views/layouts/_right_sidebar.html.slim
.right-sidebar
  = image_tag 'me.jpg'
  h2 Yoyo Coder
  p ...
  hr

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = favicon_link_tag 'favicon.ico'
    title == content_for?(:title) ? yield(:title) : "Yoyo Coder's Blog"
    == GOOGLE_FONTS_CSS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    == render 'layouts/analytics'
    = csrf_meta_tags
  body
    = yield
    == render 'layouts/footer'